project:
  type: website
  output-dir: docs
  resources: 
    - images/ #add images in this folder

website:
  title: "Las Vegas Valley Turf Tracker"
  favicon: favicon.ico
  navbar:
    right:
      - icon: github
        href: "https://github.com/yxing82/CASA0025_Final_Project"
  # sidebar: # commented out to remove sidebar for now, can add back if needed
  #   logo: casa_logo.png


# book:
#   title: "Las Vegas Valley Turf Tracker"
#   author: "Group Name"
#   date: "01/01/2024"
#   chapters:
#     - index.qmd
  

#   repo-actions: [edit]
#   downloads: [pdf, epub]
#   sharing: [twitter, facebook]
#   favicon: favicon.ico
#   sidebar:
#     logo: casa_logo.png
  
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
    css: styles.css
